name: LMGTFY
version: ${pluginversion}
main: org.royaldev.lmgtfy.LMGTFYPlugin
author: jkcclemens
description: Creates LMGTFY links on the fly.

commands:
  lmgtfy:
    description: Sends an LMGTFY link.
    usage: <command> (player) [query]

permissions:
  lmgtfy.lmgtfy:
    description: Allows /lmgtfy
    default: op
  lmgtfy.autoshorten:
    description: Allows for links to be shortened automatically in chat
    default: false
